language: python
python:
    - "2.7"
    - "3.3"
    - "pypy"
env:
    - DJANGO_VERSION=1.5.2
    - DJANGO_VERSION=1.6
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - pip install coveralls --use-mirrors
    - pip install mock --use-mirrors
    - pip install south --use-mirrors
    - pip install nose
    - pip install testfixtures
script:
    - python setup.py build
    - python setup.py nosetests --verbosity 2 --with-coverage --cover-tests --cover-erase
after_success:
    - coveralls
